---
- hosts: [production]
  become: yes
  tasks:
    - name: Installing vim, git, and curl package
      apt: name={{ item }} state=present
      with_items:
         - vim
         - git
         - curl
